version: '3.8'

services:

  postgres:
    image: postgres:11.13
    container_name: telros
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: telros
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: