server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: telros

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml
    #drop-first: true

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    open-in-view: false
